sudo: required

services:
- docker

script:
- docker build -t bentolor/idea-cli-inspector .
- mkdir -p `pwd`/target && chmod 777 `pwd`/target
- docker run --rm -v `pwd`:/project bentolor/idea-cli-inspector -v -r /project
